/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnualMonthlyAverage: typeof import('./src/components/dashboard/AnnualMonthlyAverage.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    ChartComponent: typeof import('./src/components/dashboard/ChartComponent.vue')['default']
    ColorModeSwitcher: typeof import('./src/components/general/ColorModeSwitcher.vue')['default']
    ContributionPerPerson: typeof import('./src/components/general/ContributionPerPerson.vue')['default']
    EditableComment: typeof import('./src/components/general/EditableComment.vue')['default']
    EditableNumberInput: typeof import('./src/components/general/EditableNumberInput.vue')['default']
    InvoicesPerMonthList: typeof import('./src/components/editMonth/InvoicesPerMonthList.vue')['default']
    LanguageSelector: typeof import('./src/components/general/LanguageSelector.vue')['default']
    MonthlySum: typeof import('./src/components/general/MonthlySum.vue')['default']
    MonthOverview: typeof import('./src/components/general/MonthOverview.vue')['default']
    NavBar: typeof import('./src/components/general/NavBar.vue')['default']
    NumberOfInvoices: typeof import('./src/components/general/NumberOfInvoices.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleSelect: typeof import('./src/components/general/SingleSelect.vue')['default']
  }
  export interface GlobalDirectives {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
